star:
    genome: /hg38_ref_location/Homo_sapiens_assembly38.fasta
    index: /hg38_ref_location/star_index_gencode38
    gtf: /hg38_ref_location/gencode.v38.annotation.gtf
    sjdbOverhang: 150

data:
    fastq: /fastq/raw
    trimmed: /fastq/trimmed

region_of_interest:
    - "''chr1:151401724-151460494''"
    - "''chr1:173823653-173859808''"

samples:
  "SAMPLE1":
    "reads":
      "r1": "SAMPLE1_R1.fastq.gz"
      "r2": "SAMPLE1_R2.fastq.gz"
    "variations":
      "default":
      - "default"
  "SAMPLE2":
    "reads":
      "r1": "SAMPLE2_R1.fastq.gz"
      "r2": "SAMPLE2_R2.fastq.gz"
    "variations":
      "default":
      - "default"

config:
    star:
        default:
            - "--outSAMtype BAM Unsorted"
            - "--outSAMattributes NH HI AS NM MD"
            - "--outFilterMultimapNmax 20"
            - "--alignSJoverhangMin 6"
            - "--alignSJDBoverhangMin 6"
            - "--outFilterMismatchNmax 10"      
            - "--outFilterMismatchNoverLmax 0.3"
            - "--alignIntronMin 21"
            - "--alignIntronMax 1000000"
            - "--alignMatesGapMax 0"
            - "--outFilterType BySJout"
            - "--outFilterScoreMinOverLread 0.66"
            - "--outFilterMatchNminOverLread 0.66"
            - "--outSAMstrandField intronMotif"
            - "--outFilterIntronMotifs None"
            - "--alignSoftClipAtReferenceEnds Yes"
            - "--quantMode GeneCounts"
            - "--outSAMunmapped Within"
            - "--chimSegmentMin 12"
            - "--chimJunctionOverhangMin 12"
            - "--chimOutType WithinBAM"
            - "--chimMainSegmentMultNmax 10"
            - "--outSJfilterCountUniqueMin 3 1 1 1"